### ISSUE TITLE
Feature request: Load Custom Demand/Gen Profiles .csv

### ISSUE THREAD

**Issue by apalomES** [Breakthrough-Energy/PowerSimData#547]
# :rocket:
- [x] Is your feature request essential for your project?

### Describe the workflow you want to enable
I would like the BES model to allow users to define custom demand/gen profiles. In the standalone/plug install, demand, hydro, solar, wind profile csvs are in the plug/scenario_data/raw/usa_tamu/ directory. Editing these profiles directly does not change the scenario profile in the BES model (i.e. Jupyter Notebook). This functionality would strengthen the BES model's utility in industry. 

### Describe your proposed implementation
Could the Input Class allow users to define an external file path to .csvs with custome profiles. 
https://github.com/Breakthrough-Energy/PowerSimData/blob/56d34905b8e2ea921cd498940c60189a62168638/powersimdata/input/input_data.py#L60

### Describe alternatives you've considered, if relevant
Hacking.

### Additional context
The attached demand_vJan2021.csv is an example csv that I would like to be able to load into my BES model. This is a trivial example with the first 3 days of the year zero'd out. 

[demand_vJan2021_es.csv](https://github.com/Breakthrough-Energy/PowerSimData/files/7171282/demand_vJan2021_es.csv)

**Comment by danielolsen** [comment]
Are you hoping to be able to define one-off profiles for a single Scenario, or an alternative profile to be potentially shared across many Scenarios?

Looking into this a bit, it seems like we may we able to add a **version.json** file in the appropriate location that would allow you to define a local profile which could be assigned to a scenario when it is being created, and would therefore automatically be used to prepare inputs for the simulation engine and for post-simulation analysis: https://github.com/Breakthrough-Energy/PowerSimData/blob/56d34905b8e2ea921cd498940c60189a62168638/powersimdata/data_access/profile_helper.py#L83. @jon-hagg might have a better idea of how this can be done, since he added this code in #419.

**Comment by jon-hagg** [comment]
The code that Daniel linked is the relevant bit - basically we will combine the profile versions found in the version.json from blob storage with the ones found in the version.json (if it exists) located in the container's `~/ScenarioData` folder. At the moment, the easiest way to use a custom profile is to add the two files - the version.json specifying your profile's name, and the profile itself, which I believe could be placed outside the container, in the `rootdir/raw/usa_tamu` folder at the root of the plug repo. 

I haven't actually done this in a while, but I know it's worked before and the data should persist in the docker volume so it would be a one time thing. Hopefully we will find some time to simplify this process.

**Comment by jon-hagg** [comment]
@apalomES the attached PR makes it so there is no need to add a local version.json. Rather, you could place any custom profile in the `rootdir/raw/usa_tamu` folder (relative to the plug repo), and select it when building a scenario. This may require restarting or replacing any running containers.. let me know if there are any issues.

**Comment by jon-hagg** [comment]
One more thing I forgot to mention, but to use this code, the docker-compose.yml should reference the `postreise:latest` image, rather than `:stable`. May or may not be applicable depending on when you last pulled the plug repo.
