### ISSUE TITLE
Expand building phase of a scenario to grid models in form of PyPSA Network object

### ISSUE THREAD

**Issue by rouille** [Breakthrough-Energy/PowerSimData#632]
- [x] Base class is named  `_Builder` 
- [x] Child classes are `FromCSV` and `FromPyPSA`
- [x] Factory method creates the desired object based in the `set_grid` method of the `Create` class using the `grid_model` parameter.

**Comment by danielolsen** [comment]
If we get an arbitrary `Network` object (i.e. not one of the pre-prepared European Networks via Zenodo), could we enable retrieval of the input time-series profiles by indicating in the ScenarioList that the grid_model and profile versions are e.g. `None`, which tells PowerSimData to try to retrieve the information from the `tmp` folder on the server? It's a bit of an abuse of folder which had been `temporary`, but I'm not sure how else it can be available to a user who's not the person who created and prepared the Scenario.

This is probably a lower priority than enabling the pre-defined European Networks, which should be easier because the information is retrievable by anyone (see https://github.com/Breakthrough-Energy/PowerSimData/issues/630#issuecomment-1137724060).

**Comment by rouille** [comment]
Thanks for bringing this up, I did not think about it yet. I believe there are several options (all with pros and cons) but whatever option we choose, we need to populate all the columns in the scenario list file. Profiles version set to `None` (or `from_pypsa`, `from_pypsa-eur`, `from_pypsa-tamu`, etc.) would  work. I believe the `grid_model` can still be set to `usa_tamu`/`hifld`/`europe_tub` whatever is its provenance (CSV files, PyPSA from zenodo or PyPSA build from scripts/snamemake)

Then, there is a question of the engine used.
* If the grid comes from a PyPSA `Network` object and we run a PCM with REISE.jl the transformed profiles will be available in the *tmp* folder, we can fetch them (what you propose) but we won't be able to use the current `get_solar`, `get_wind`, etc methods that use the transform the base profiles using the change table. We can save the base profiles extracted from the `Network` object in *input* together with the change table, fetch them and use the same `get_solar`, etc methods.
* if the grid comes from a PyPSA `Network` object and we run a CEM with PyPSA, the engine will take a `Network` object enclosing the profiles and the output will (I guess) enclose the profiles that we can extract in the `extract_data` script and save them in the *output* folder. For CEM, we will have a dedicated child class of `Analyze` and we can there fetch the profiles.

It is exciting.
